apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: image-blocker-webook
webhooks:

  - name: image-blocker-blocker.default.svc # 这里的名字为集群创建证书的时候指定的访问域名
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        failurePolicy: Ignore
        sideEffects: None
        admissionReviewVersions: ["v1", "v1beta1"]
        clientConfig:
        caBundle: "生成的cert文件内容,经过base加密后的结果"
        service:
        name: image-blocker-webhook
        namespace: default
        port: 9527
        path: "/"
